"""gemini

Revision ID: 9b0f3a1daf54
Revises: e355829f2e6c
Create Date: 2025-07-24 13:46:01.224394

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9b0f3a1daf54"
down_revision: str | Sequence[str] | None = "e355829f2e6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
