"""models

Revision ID: b6bb05fa1afa
Revises:
Create Date: 2025-07-23 15:04:07.324216

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b6bb05fa1afa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
