"""again

Revision ID: fa28db0961d0
Revises: 9b0f3a1daf54
Create Date: 2025-07-24 13:56:33.002051

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fa28db0961d0"
down_revision: str | Sequence[str] | None = "9b0f3a1daf54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
